-- Schema base para LogiWMS-Pro (PostgreSQL)
-- Versao otimizada para carga real (AWS/RDS)

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS warehouses (
  id VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  location VARCHAR(255),
  manager_name VARCHAR(255),
  manager_email VARCHAR(255),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  role TEXT NOT NULL,
  status TEXT DEFAULT 'Ativo',
  last_access TIMESTAMPTZ,
  avatar TEXT,
  password TEXT NOT NULL,
  modules JSONB NOT NULL DEFAULT '[]'::JSONB,
  allowed_warehouses JSONB NOT NULL DEFAULT '[]'::JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cost_centers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  manager TEXT,
  budget DECIMAL(15, 2) DEFAULT 0,
  status TEXT DEFAULT 'Ativo',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS vendors (
  id TEXT PRIMARY KEY,
  id_fornecedor BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  razao_social VARCHAR(150) NOT NULL,
  nome_fantasia VARCHAR(100),
  cnpj VARCHAR(14) NOT NULL,
  telefone VARCHAR(20),
  name TEXT,
  category TEXT,
  contact TEXT,
  email TEXT,
  status TEXT DEFAULT 'Ativo',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS vehicles (
  plate VARCHAR(20) PRIMARY KEY,
  model TEXT,
  type TEXT,
  status TEXT DEFAULT 'Disponivel',
  last_maintenance TIMESTAMPTZ,
  cost_center TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabelas do modulo Gestao de Frota (DER reestruturado)
CREATE TABLE IF NOT EXISTS fleet_vehicles (
  placa VARCHAR(20) PRIMARY KEY,
  renavam TEXT,
  chassi TEXT,
  classe TEXT,
  cor TEXT,
  ano_modelo INTEGER,
  ano_fabricacao INTEGER,
  cidade TEXT,
  estado TEXT,
  proprietario TEXT,
  cod_centro_custo TEXT,
  desc_centro_custo TEXT,
  desc_modelo TEXT,
  desc_marca TEXT,
  desc_combustivel TEXT,
  km_atual INTEGER DEFAULT 0,
  km_anterior INTEGER DEFAULT 0,
  dta_ult_manutencao TIMESTAMPTZ,
  dta_prox_manutencao TIMESTAMPTZ,
  km_prox_manutencao INTEGER DEFAULT 0,
  gestao_multa TEXT DEFAULT 'NAO',
  setor_veiculo TEXT,
  responsavel_veiculo TEXT,
  source_module TEXT NOT NULL DEFAULT 'gestao_frota' CHECK (source_module IN ('gestao_frota', 'oficina')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS fleet_people (
  cpf VARCHAR(14) PRIMARY KEY,
  matricula TEXT,
  nome_completo TEXT NOT NULL,
  id_perfil TEXT,
  id_funcao TEXT,
  cod_centro_custo TEXT,
  cnh TEXT,
  categoria TEXT,
  validade_cnh TIMESTAMPTZ,
  toxico_venc TIMESTAMPTZ,
  telefone TEXT,
  email TEXT,
  status TEXT DEFAULT 'ATIVO',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS fleet_fines (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  placa VARCHAR(20) REFERENCES fleet_vehicles(placa) ON UPDATE CASCADE ON DELETE SET NULL,
  ain TEXT,
  data TIMESTAMPTZ,
  hora TEXT,
  local TEXT,
  valor DECIMAL(12,2) DEFAULT 0,
  gravidade TEXT,
  enquadramento TEXT,
  condutor TEXT,
  status TEXT DEFAULT 'PENDENTE',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS fleet_tachograph_checks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  placa VARCHAR(20) REFERENCES fleet_vehicles(placa) ON UPDATE CASCADE ON DELETE SET NULL,
  num_certificado TEXT,
  dta_afericao TIMESTAMPTZ,
  dta_vencimento TIMESTAMPTZ,
  valor_taxa DECIMAL(12,2) DEFAULT 0,
  status TEXT DEFAULT 'REGULAR',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS fleet_rntrc_records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  razao_social TEXT NOT NULL,
  documento TEXT,
  rntrc TEXT,
  categoria TEXT,
  vencimento TIMESTAMPTZ,
  status TEXT DEFAULT 'ATIVO',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS fleet_fiscal_obligations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  placa VARCHAR(20) REFERENCES fleet_vehicles(placa) ON UPDATE CASCADE ON DELETE SET NULL,
  tipo TEXT,
  exercicio INTEGER,
  vencimento TIMESTAMPTZ,
  valor DECIMAL(12,2) DEFAULT 0,
  status TEXT DEFAULT 'PENDENTE',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS inventory (
  sku VARCHAR(50) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  location TEXT,
  batch TEXT,
  expiry TEXT,
  quantity INTEGER DEFAULT 0,
  status TEXT DEFAULT 'disponivel',
  image_url TEXT,
  category TEXT,
  min_qty INTEGER DEFAULT 0,
  max_qty INTEGER DEFAULT 0,
  unit TEXT DEFAULT 'UN',
  lead_time INTEGER DEFAULT 7,
  safety_stock INTEGER DEFAULT 5,
  abc_category TEXT,
  last_counted_at TIMESTAMPTZ,
  warehouse_id VARCHAR(50) REFERENCES warehouses(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS movements (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sku VARCHAR(50) REFERENCES inventory(sku),
  product_name TEXT,
  type TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  "user" TEXT,
  location TEXT,
  reason TEXT,
  order_id TEXT,
  warehouse_id VARCHAR(50) REFERENCES warehouses(id)
);

CREATE TABLE IF NOT EXISTS purchase_orders (
  id TEXT PRIMARY KEY,
  vendor TEXT,
  request_date TIMESTAMPTZ DEFAULT NOW(),
  status TEXT DEFAULT 'requisicao',
  priority TEXT DEFAULT 'normal',
  total DECIMAL(15, 2) DEFAULT 0,
  requester TEXT,
  items JSONB NOT NULL DEFAULT '[]'::JSONB,
  quotes JSONB NOT NULL DEFAULT '[]'::JSONB,
  selected_quote_id TEXT,
  sent_to_vendor_at TIMESTAMPTZ,
  received_at TIMESTAMPTZ,
  quotes_added_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  rejected_at TIMESTAMPTZ,
  vendor_order_number TEXT,
  approval_history JSONB NOT NULL DEFAULT '[]'::JSONB,
  plate TEXT,
  cost_center TEXT,
  warehouse_id VARCHAR(50) REFERENCES warehouses(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS material_requests (
  id TEXT PRIMARY KEY,
  sku VARCHAR(50) REFERENCES inventory(sku),
  name TEXT,
  qty INTEGER NOT NULL,
  plate TEXT,
  dept TEXT,
  priority TEXT,
  status TEXT DEFAULT 'aprovacao',
  cost_center TEXT,
  warehouse_id VARCHAR(50) REFERENCES warehouses(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cyclic_batches (
  id TEXT PRIMARY KEY,
  status TEXT DEFAULT 'aberto',
  scheduled_date TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  accuracy_rate DECIMAL(5, 2),
  total_items INTEGER DEFAULT 0,
  divergent_items INTEGER DEFAULT 0,
  warehouse_id VARCHAR(50) REFERENCES warehouses(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cyclic_counts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id TEXT REFERENCES cyclic_batches(id),
  sku VARCHAR(50) REFERENCES inventory(sku),
  expected_qty INTEGER NOT NULL,
  counted_qty INTEGER,
  status TEXT DEFAULT 'pendente',
  notes TEXT,
  counted_at TIMESTAMPTZ,
  warehouse_id VARCHAR(50) REFERENCES warehouses(id)
);

CREATE TABLE IF NOT EXISTS notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT DEFAULT 'info',
  read BOOLEAN DEFAULT false,
  user_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  entity TEXT NOT NULL,
  entity_id TEXT,
  module TEXT NOT NULL,
  action TEXT NOT NULL,
  actor TEXT,
  actor_id TEXT,
  warehouse_id VARCHAR(50),
  before_data JSONB,
  after_data JSONB,
  meta JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indices operacionais
CREATE INDEX IF NOT EXISTS idx_users_role_status ON users(role, status);
CREATE INDEX IF NOT EXISTS idx_users_last_access ON users(last_access DESC);
CREATE INDEX IF NOT EXISTS idx_users_modules_gin ON users USING GIN (modules);
CREATE INDEX IF NOT EXISTS idx_users_allowed_warehouses_gin ON users USING GIN (allowed_warehouses);

CREATE INDEX IF NOT EXISTS idx_inventory_warehouse ON inventory(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_inventory_status ON inventory(status);
CREATE INDEX IF NOT EXISTS idx_inventory_category ON inventory(category);
CREATE INDEX IF NOT EXISTS idx_inventory_name_lower ON inventory ((lower(name)));
CREATE UNIQUE INDEX IF NOT EXISTS uq_vendors_id_fornecedor ON vendors(id_fornecedor);
CREATE INDEX IF NOT EXISTS idx_vendors_cnpj_digits ON vendors ((regexp_replace(COALESCE(cnpj, ''), '[^0-9]', '', 'g')));
CREATE INDEX IF NOT EXISTS idx_vendors_razao_social_lower ON vendors ((lower(COALESCE(razao_social, name, ''))));
CREATE INDEX IF NOT EXISTS idx_vendors_razao_social_norm ON vendors ((lower(regexp_replace(btrim(COALESCE(razao_social, name, '')), '\s+', ' ', 'g'))));
CREATE INDEX IF NOT EXISTS idx_fleet_vehicles_centro_custo ON fleet_vehicles(cod_centro_custo);
CREATE INDEX IF NOT EXISTS idx_fleet_vehicles_source_module_placa ON fleet_vehicles(source_module, placa);
CREATE INDEX IF NOT EXISTS idx_fleet_people_centro_custo ON fleet_people(cod_centro_custo);
CREATE INDEX IF NOT EXISTS idx_fleet_fines_placa_data ON fleet_fines(placa, data DESC);
CREATE INDEX IF NOT EXISTS idx_fleet_tacho_placa_venc ON fleet_tachograph_checks(placa, dta_vencimento DESC);
CREATE INDEX IF NOT EXISTS idx_fleet_rntrc_status_venc ON fleet_rntrc_records(status, vencimento DESC);
CREATE INDEX IF NOT EXISTS idx_fleet_fiscal_placa_venc ON fleet_fiscal_obligations(placa, vencimento DESC);

CREATE INDEX IF NOT EXISTS idx_movements_warehouse_timestamp ON movements(warehouse_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_movements_sku_timestamp ON movements(sku, timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_po_warehouse_request_date ON purchase_orders(warehouse_id, request_date DESC);
CREATE INDEX IF NOT EXISTS idx_po_status_priority ON purchase_orders(status, priority);
CREATE INDEX IF NOT EXISTS idx_po_items_gin ON purchase_orders USING GIN (items);
CREATE INDEX IF NOT EXISTS idx_po_quotes_gin ON purchase_orders USING GIN (quotes);
CREATE INDEX IF NOT EXISTS idx_po_approval_history_gin ON purchase_orders USING GIN (approval_history);

CREATE INDEX IF NOT EXISTS idx_requests_warehouse_created ON material_requests(warehouse_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_requests_status_priority ON material_requests(status, priority);

CREATE INDEX IF NOT EXISTS idx_notifications_user_read_created ON notifications(user_id, read, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cyclic_batches_warehouse_created ON cyclic_batches(warehouse_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cyclic_counts_batch ON cyclic_counts(batch_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_module_created ON audit_logs(module, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity, entity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_created ON audit_logs(actor, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action_created ON audit_logs(action, created_at DESC);

-- Auditoria em trigger para tabelas centrais de cadastro
CREATE OR REPLACE FUNCTION audit_capture_row_change()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  action_value TEXT;
  entity_id_value TEXT;
  actor_value TEXT;
  actor_id_value TEXT;
  module_value TEXT;
  warehouse_value TEXT;
  before_payload JSONB;
  after_payload JSONB;
  meta_payload JSONB;
  id_column TEXT;
BEGIN
  IF TG_TABLE_NAME = 'audit_logs' THEN
    RETURN COALESCE(NEW, OLD);
  END IF;

  id_column := COALESCE(NULLIF(TG_ARGV[1], ''), 'id');
  module_value := COALESCE(NULLIF(current_setting('app.audit_module', true), ''), NULLIF(TG_ARGV[0], ''), TG_TABLE_NAME);
  actor_value := COALESCE(NULLIF(current_setting('app.audit_actor', true), ''), current_user);
  actor_id_value := NULLIF(current_setting('app.audit_actor_id', true), '');

  action_value := CASE TG_OP
    WHEN 'INSERT' THEN 'create'
    WHEN 'UPDATE' THEN 'update'
    WHEN 'DELETE' THEN 'delete'
    ELSE lower(TG_OP)
  END;

  IF TG_OP = 'INSERT' THEN
    before_payload := NULL;
    after_payload := to_jsonb(NEW);
    entity_id_value := COALESCE(after_payload ->> id_column, '');
    warehouse_value := NULLIF(after_payload ->> 'warehouse_id', '');
  ELSIF TG_OP = 'UPDATE' THEN
    before_payload := to_jsonb(OLD);
    after_payload := to_jsonb(NEW);
    entity_id_value := COALESCE(after_payload ->> id_column, before_payload ->> id_column, '');
    warehouse_value := COALESCE(NULLIF(after_payload ->> 'warehouse_id', ''), NULLIF(before_payload ->> 'warehouse_id', ''));
  ELSE
    before_payload := to_jsonb(OLD);
    after_payload := NULL;
    entity_id_value := COALESCE(before_payload ->> id_column, '');
    warehouse_value := NULLIF(before_payload ->> 'warehouse_id', '');
  END IF;

  meta_payload := jsonb_build_object(
    'source', 'db_trigger',
    'table', TG_TABLE_NAME,
    'operation', TG_OP,
    'txid', txid_current()
  );

  INSERT INTO audit_logs (
    entity,
    entity_id,
    module,
    action,
    actor,
    actor_id,
    warehouse_id,
    before_data,
    after_data,
    meta
  )
  VALUES (
    TG_TABLE_NAME,
    NULLIF(entity_id_value, ''),
    module_value,
    action_value,
    actor_value,
    actor_id_value,
    warehouse_value,
    before_payload,
    after_payload,
    meta_payload
  );

  RETURN COALESCE(NEW, OLD);
EXCEPTION WHEN others THEN
  RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS trg_audit_vendors ON vendors;
CREATE TRIGGER trg_audit_vendors
AFTER INSERT OR UPDATE OR DELETE ON vendors
FOR EACH ROW
EXECUTE FUNCTION audit_capture_row_change('cadastro_geral', 'id');

DROP TRIGGER IF EXISTS trg_audit_inventory ON inventory;
CREATE TRIGGER trg_audit_inventory
AFTER INSERT OR UPDATE OR DELETE ON inventory
FOR EACH ROW
EXECUTE FUNCTION audit_capture_row_change('cadastro_geral', 'sku');

DROP TRIGGER IF EXISTS trg_audit_fleet_vehicles ON fleet_vehicles;
CREATE TRIGGER trg_audit_fleet_vehicles
AFTER INSERT OR UPDATE OR DELETE ON fleet_vehicles
FOR EACH ROW
EXECUTE FUNCTION audit_capture_row_change('gestao_frota', 'placa');

-- Seed basico
INSERT INTO warehouses (id, name, description, location, is_active)
VALUES
  ('ARMZ28', 'Armazem Principal', 'Operacoes gerais de armazenamento e distribuicao', 'Manaus - AM', true),
  ('ARMZ33', 'Conferencia de Carga em Tempo Real', 'Recebimento, conferencia e validacao de carga', 'Manaus - AM', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO users (id, name, email, role, status, password, modules, allowed_warehouses)
VALUES (
  'admin-001',
  'Administrador',
  'admin@nortetech.com',
  'admin',
  'Ativo',
  'pbkdf2$310000$c69ffaeaeaf017b7f94270ab3a61d55b$8d5b4fd072c9044b957eb432bdf26f03ff1b50a7859ca7b370b0f896356f356a',
  '["dashboard","recebimento","movimentacoes","estoque","expedicao","inventario_ciclico","compras","cadastro","relatorios","configuracoes"]'::jsonb,
  '["ARMZ28","ARMZ33"]'::jsonb
)
ON CONFLICT (id) DO NOTHING;

-- ============================================
-- TABELAS DO MÓDULO DE OFICINA (WORKSHOP)
-- ============================================

-- Mecânicos
CREATE TABLE IF NOT EXISTS mechanics (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  specialty TEXT,
  shift TEXT DEFAULT 'manha',
  status TEXT DEFAULT 'disponivel',
  current_work_orders JSONB NOT NULL DEFAULT '[]'::JSONB,
  orders_completed INTEGER DEFAULT 0,
  avg_hours_per_order DECIMAL(5, 2) DEFAULT 0,
  on_time_rate DECIMAL(5, 2) DEFAULT 100,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ordens de Serviço
CREATE TABLE IF NOT EXISTS work_orders (
  id TEXT PRIMARY KEY,
  vehicle_plate VARCHAR(20) REFERENCES vehicles(plate),
  vehicle_model TEXT,
  status TEXT DEFAULT 'aguardando',
  type TEXT DEFAULT 'corretiva',
  priority TEXT DEFAULT 'normal',
  mechanic_id TEXT REFERENCES mechanics(id),
  mechanic_name TEXT,
  supervisor_id TEXT,
  supervisor_name TEXT,
  workshop_unit TEXT,
  description TEXT NOT NULL,
  services JSONB NOT NULL DEFAULT '[]'::JSONB,
  parts JSONB NOT NULL DEFAULT '[]'::JSONB,
  opened_at TIMESTAMPTZ DEFAULT NOW(),
  closed_at TIMESTAMPTZ,
  estimated_hours INTEGER DEFAULT 0,
  actual_hours DECIMAL(5, 2),
  status_timers JSONB NOT NULL DEFAULT '{}'::JSONB,
  total_seconds INTEGER DEFAULT 0,
  last_status_change TIMESTAMPTZ,
  is_timer_active BOOLEAN DEFAULT false,
  cost_center TEXT,
  cost_labor DECIMAL(10, 2) DEFAULT 0,
  cost_parts DECIMAL(10, 2) DEFAULT 0,
  cost_third_party DECIMAL(10, 2) DEFAULT 0,
  cost_total DECIMAL(10, 2) DEFAULT 0,
  created_by TEXT,
  warehouse_id VARCHAR(50) REFERENCES warehouses(id),
  locked_by TEXT,
  locked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Logs de status das ordens de serviço
CREATE TABLE IF NOT EXISTS work_order_logs (
  id TEXT PRIMARY KEY,
  work_order_id TEXT REFERENCES work_orders(id),
  previous_status TEXT,
  new_status TEXT,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  user_id TEXT,
  duration_seconds INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Atribuições de serviços por mecânico (produtividade)
CREATE TABLE IF NOT EXISTS work_order_assignments (
  id TEXT PRIMARY KEY,
  work_order_id TEXT REFERENCES work_orders(id),
  service_id TEXT,
  previous_mechanic_id TEXT,
  previous_mechanic_name TEXT,
  new_mechanic_id TEXT,
  new_mechanic_name TEXT,
  service_category TEXT,
  service_description TEXT,
  timestamp TIMESTAMPTZ DEFAULT NOW(),
  accumulated_seconds INTEGER DEFAULT 0,
  created_by TEXT,
  warehouse_id VARCHAR(50) REFERENCES warehouses(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Planos de Manutenção Preventiva
CREATE TABLE IF NOT EXISTS maintenance_plans (
  id TEXT PRIMARY KEY,
  vehicle_type TEXT NOT NULL,
  vehicle_model TEXT,
  name TEXT NOT NULL,
  trigger_type TEXT NOT NULL,
  trigger_value INTEGER NOT NULL,
  services JSONB NOT NULL DEFAULT '[]'::JSONB,
  checklist JSONB NOT NULL DEFAULT '[]'::JSONB,
  estimated_hours INTEGER DEFAULT 0,
  estimated_cost DECIMAL(10, 2) DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Manutenções Agendadas
CREATE TABLE IF NOT EXISTS scheduled_maintenance (
  id TEXT PRIMARY KEY,
  vehicle_plate VARCHAR(20) REFERENCES vehicles(plate),
  plan_id TEXT REFERENCES maintenance_plans(id),
  plan_name TEXT,
  due_km INTEGER,
  due_date TIMESTAMPTZ,
  status TEXT DEFAULT 'pendente',
  work_order_id TEXT REFERENCES work_orders(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Checklists de Inspeção
CREATE TABLE IF NOT EXISTS inspection_checklists (
  id TEXT PRIMARY KEY,
  vehicle_plate VARCHAR(20) REFERENCES vehicles(plate),
  type TEXT NOT NULL,
  date TIMESTAMPTZ DEFAULT NOW(),
  inspector TEXT NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::JSONB,
  status TEXT DEFAULT 'aprovado',
  notes TEXT,
  photos JSONB DEFAULT '[]'::JSONB,
  work_order_id TEXT REFERENCES work_orders(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===== TABELAS EXPANDIDAS PARA MÓDULO DE OFICINA AVANÇADO =====

-- Detalhes do veículo (expandido)
CREATE TABLE IF NOT EXISTS vehicle_details (
  plate VARCHAR(20) PRIMARY KEY REFERENCES vehicles(plate),
  chassis TEXT,
  year INTEGER,
  mileage INTEGER DEFAULT 0,
  engine_hours INTEGER DEFAULT 0,
  cost_center TEXT,
  documents JSONB DEFAULT '[]'::JSONB,
  components JSONB DEFAULT '[]'::JSONB,
  maintenance_plan_id TEXT REFERENCES maintenance_plans(id),
  next_service_km INTEGER,
  next_service_date TIMESTAMPTZ,
  status_operacional TEXT DEFAULT 'operacional',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Eventos do veículo (histórico)
CREATE TABLE IF NOT EXISTS vehicle_events (
  id TEXT PRIMARY KEY,
  vehicle_plate VARCHAR(20) REFERENCES vehicles(plate),
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  date TIMESTAMPTZ DEFAULT NOW(),
  mechanic TEXT,
  workshop TEXT,
  os_id TEXT REFERENCES work_orders(id),
  status TEXT,
  cost DECIMAL(10,2),
  parts JSONB DEFAULT '[]'::JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Planos de manutenção expandidos
CREATE TABLE IF NOT EXISTS maintenance_plans_expanded (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  vehicle_type TEXT NOT NULL,
  vehicle_model TEXT,
  operation_type TEXT DEFAULT 'normal',
  triggers JSONB DEFAULT '[]'::JSONB,
  parts JSONB DEFAULT '[]'::JSONB,
  checklist_sections JSONB DEFAULT '[]'::JSONB,
  estimated_hours INTEGER DEFAULT 0,
  estimated_cost DECIMAL(10,2) DEFAULT 0,
  services JSONB DEFAULT '[]'::JSONB,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT
);

-- Planos ativos por veículo
CREATE TABLE IF NOT EXISTS active_plans (
  id TEXT PRIMARY KEY,
  vehicle_plate VARCHAR(20) REFERENCES vehicles(plate),
  plan_id TEXT REFERENCES maintenance_plans_expanded(id),
  plan_name TEXT,
  current_km INTEGER DEFAULT 0,
  target_km INTEGER,
  percentage INTEGER DEFAULT 0,
  remaining_km INTEGER,
  status TEXT DEFAULT 'em_conformidade',
  next_service_description TEXT,
  next_service_due_km INTEGER,
  next_service_due_date TIMESTAMPTZ,
  days_remaining INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Milestones de manutenção
CREATE TABLE IF NOT EXISTS maintenance_milestones (
  id TEXT PRIMARY KEY,
  schedule_id TEXT NOT NULL,
  km INTEGER NOT NULL,
  date TIMESTAMPTZ,
  description TEXT NOT NULL,
  status TEXT DEFAULT 'planejado',
  type TEXT DEFAULT 'revisao',
  cost DECIMAL(10,2),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Cronogramas preventivos
CREATE TABLE IF NOT EXISTS preventive_schedules (
  id TEXT PRIMARY KEY,
  vehicle_plate VARCHAR(20) REFERENCES vehicles(plate),
  vehicle_model TEXT,
  plan_id TEXT REFERENCES maintenance_plans_expanded(id),
  plan_name TEXT,
  milestones JSONB DEFAULT '[]'::JSONB,
  next_service_description TEXT,
  next_service_km INTEGER,
  next_service_estimated_date TIMESTAMPTZ,
  next_service_priority TEXT DEFAULT 'media',
  next_service_parts JSONB DEFAULT '[]'::JSONB,
  next_service_total_cost DECIMAL(10,2),
  next_service_estimated_duration TEXT,
  predictive_analysis JSONB DEFAULT '{}'::JSONB,
  system_health JSONB DEFAULT '[]'::JSONB,
  cost_per_km DECIMAL(10,2),
  availability DECIMAL(5,2),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Templates de inspeção
CREATE TABLE IF NOT EXISTS inspection_templates (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  version TEXT DEFAULT '1.0',
  vehicle_model TEXT,
  description TEXT,
  sections JSONB DEFAULT '[]'::JSONB,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by TEXT
);

-- Alertas de manutenção
CREATE TABLE IF NOT EXISTS maintenance_alerts (
  id TEXT PRIMARY KEY,
  type TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  vehicle_plate VARCHAR(20) REFERENCES vehicles(plate),
  severity TEXT DEFAULT 'info',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  resolved_at TIMESTAMPTZ,
  action TEXT
);

-- Índices para tabelas de oficina
CREATE INDEX IF NOT EXISTS idx_work_orders_warehouse ON work_orders(warehouse_id);
CREATE INDEX IF NOT EXISTS idx_work_orders_status ON work_orders(status);
CREATE INDEX IF NOT EXISTS idx_work_orders_mechanic ON work_orders(mechanic_id);
CREATE INDEX IF NOT EXISTS idx_work_orders_vehicle ON work_orders(vehicle_plate);
CREATE INDEX IF NOT EXISTS idx_work_orders_opened_at ON work_orders(opened_at DESC);
CREATE INDEX IF NOT EXISTS idx_work_orders_services_gin ON work_orders USING GIN (services);
CREATE INDEX IF NOT EXISTS idx_work_orders_parts_gin ON work_orders USING GIN (parts);
CREATE INDEX IF NOT EXISTS idx_work_orders_status_timers_gin ON work_orders USING GIN (status_timers);

CREATE INDEX IF NOT EXISTS idx_work_order_logs_order ON work_order_logs(work_order_id);
CREATE INDEX IF NOT EXISTS idx_work_order_logs_timestamp ON work_order_logs(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_work_order_assignments_order ON work_order_assignments(work_order_id);
CREATE INDEX IF NOT EXISTS idx_work_order_assignments_mechanic ON work_order_assignments(new_mechanic_id);
CREATE INDEX IF NOT EXISTS idx_work_order_assignments_timestamp ON work_order_assignments(timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_mechanics_status ON mechanics(status);
CREATE INDEX IF NOT EXISTS idx_mechanics_current_orders_gin ON mechanics USING GIN (current_work_orders);

CREATE INDEX IF NOT EXISTS idx_scheduled_maintenance_vehicle ON scheduled_maintenance(vehicle_plate);
CREATE INDEX IF NOT EXISTS idx_scheduled_maintenance_status ON scheduled_maintenance(status);
CREATE INDEX IF NOT EXISTS idx_scheduled_maintenance_due_date ON scheduled_maintenance(due_date);

CREATE INDEX IF NOT EXISTS idx_inspection_checklists_vehicle ON inspection_checklists(vehicle_plate);
CREATE INDEX IF NOT EXISTS idx_inspection_checklists_type ON inspection_checklists(type);
CREATE INDEX IF NOT EXISTS idx_inspection_checklists_date ON inspection_checklists(date DESC);

-- Triggers de controle de tempo por status da OS
CREATE OR REPLACE FUNCTION work_order_apply_status_timer()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  elapsed_seconds INTEGER;
  previous_status TEXT;
  previous_timers JSONB;
  previous_value INTEGER;
  services_payload JSONB;
  has_mechanic BOOLEAN;
BEGIN
  services_payload := CASE
    WHEN NEW.services IS NULL THEN '[]'::jsonb
    WHEN jsonb_typeof(NEW.services) = 'array' THEN NEW.services
    ELSE '[]'::jsonb
  END;

  SELECT EXISTS (
    SELECT 1
    FROM jsonb_array_elements(services_payload) AS item
    WHERE COALESCE(NULLIF(item->>'mechanicId', ''), NULLIF(item->>'mechanic_id', '')) IS NOT NULL
  ) INTO has_mechanic;

  IF TG_OP = 'INSERT' THEN
    NEW.status := COALESCE(NULLIF(NEW.status, ''), 'aguardando');
    IF NEW.status = 'aguardando' AND has_mechanic THEN
      NEW.status := 'em_execucao';
    END IF;
    NEW.status_timers := COALESCE(NEW.status_timers, '{}'::JSONB);
    NEW.last_status_change := COALESCE(NEW.last_status_change, NEW.opened_at, NOW());
    NEW.is_timer_active := (NEW.status = 'em_execucao');
    RETURN NEW;
  END IF;

  NEW.status := COALESCE(NULLIF(NEW.status, ''), OLD.status, 'aguardando');
  IF NEW.status = 'aguardando' AND has_mechanic THEN
    NEW.status := 'em_execucao';
  END IF;

  IF NEW.status IS DISTINCT FROM OLD.status THEN
    previous_status := OLD.status;
    elapsed_seconds := EXTRACT(EPOCH FROM (NOW() - COALESCE(OLD.last_status_change, OLD.opened_at, NOW())))::INT;
    IF elapsed_seconds < 0 THEN
      elapsed_seconds := 0;
    END IF;

    previous_timers := COALESCE(OLD.status_timers, '{}'::JSONB);
    previous_value := COALESCE((previous_timers ->> previous_status)::INT, 0);
    NEW.status_timers := jsonb_set(previous_timers, ARRAY[previous_status], to_jsonb(previous_value + elapsed_seconds), true);
    NEW.total_seconds := COALESCE(OLD.total_seconds, 0) + elapsed_seconds;
    NEW.last_status_change := NOW();
    NEW.is_timer_active := (NEW.status = 'em_execucao');

    IF NEW.status = 'finalizada' THEN
      NEW.closed_at := COALESCE(NEW.closed_at, NOW());
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_work_orders_status_timer ON work_orders;
CREATE TRIGGER trg_work_orders_status_timer
BEFORE INSERT OR UPDATE ON work_orders
FOR EACH ROW
EXECUTE FUNCTION work_order_apply_status_timer();

DROP TRIGGER IF EXISTS trg_work_orders_status_log ON work_orders;
DROP FUNCTION IF EXISTS work_order_log_status_change();

-- Índices para tabelas expandidas
CREATE INDEX IF NOT EXISTS idx_vehicle_details_plate ON vehicle_details(plate);
CREATE INDEX IF NOT EXISTS idx_vehicle_details_status ON vehicle_details(status_operacional);
CREATE INDEX IF NOT EXISTS idx_vehicle_events_plate ON vehicle_events(vehicle_plate);
CREATE INDEX IF NOT EXISTS idx_vehicle_events_type ON vehicle_events(type);
CREATE INDEX IF NOT EXISTS idx_vehicle_events_date ON vehicle_events(date DESC);
CREATE INDEX IF NOT EXISTS idx_active_plans_plate ON active_plans(vehicle_plate);
CREATE INDEX IF NOT EXISTS idx_active_plans_status ON active_plans(status);
CREATE INDEX IF NOT EXISTS idx_maintenance_milestones_schedule ON maintenance_milestones(schedule_id);
CREATE INDEX IF NOT EXISTS idx_preventive_schedules_plate ON preventive_schedules(vehicle_plate);
CREATE INDEX IF NOT EXISTS idx_inspection_templates_model ON inspection_templates(vehicle_model);
CREATE INDEX IF NOT EXISTS idx_maintenance_alerts_plate ON maintenance_alerts(vehicle_plate);
CREATE INDEX IF NOT EXISTS idx_maintenance_alerts_severity ON maintenance_alerts(severity);

-- Seed inicial de mecânicos
INSERT INTO mechanics (id, name, specialty, shift, status)
VALUES
  ('MEC-001', 'João Silva', 'Motor e Transmissão', 'manha', 'disponivel'),
  ('MEC-002', 'Ricardo Mendes', 'Elétrica e Eletrônica', 'manha', 'disponivel'),
  ('MEC-003', 'Carlos Oliveira', 'Suspensão e Freios', 'tarde', 'disponivel')
ON CONFLICT (id) DO NOTHING;

-- Seed inicial de planos de manutenção
INSERT INTO maintenance_plans (id, vehicle_type, name, trigger_type, trigger_value, services, checklist, estimated_hours, estimated_cost)
VALUES
  ('PLAN-001', 'Caminhão', 'Revisão 10.000 km', 'km', 10000, 
   '["Troca de óleo e filtros", "Inspeção de freios", "Verificação de pneus", "Lubrificação geral"]'::jsonb,
   '[{"id":"1","description":"Nível de óleo do motor","category":"Motor","critical":true},{"id":"2","description":"Espessura das lonas de freio","category":"Freios","critical":true},{"id":"3","description":"Pressão dos pneus","category":"Pneus","critical":false}]'::jsonb,
   4, 800),
  ('PLAN-002', 'Caminhão', 'Revisão 50.000 km', 'km', 50000,
   '["Troca de óleo e filtros", "Revisão completa da suspensão", "Inspeção do sistema de freios", "Verificação da transmissão", "Troca de fluido de arrefecimento"]'::jsonb,
   '[{"id":"1","description":"Nível de óleo do motor","category":"Motor","critical":true},{"id":"2","description":"Holandagem da suspensão","category":"Suspensão","critical":true},{"id":"3","description":"Espessura dos discos de freio","category":"Freios","critical":true},{"id":"4","description":"Nível de fluido de arrefecimento","category":"Motor","critical":true}]'::jsonb,
   8, 2500),
  ('PLAN-003', 'Ônibus', 'Revisão Mensal', 'days', 30,
   '["Troca de óleo", "Inspeção de freios", "Verificação de ar condicionado", "Limpeza de filtros"]'::jsonb,
   '[{"id":"1","description":"Funcionamento do ar condicionado","category":"Elétrica","critical":false},{"id":"2","description":"Estado das palhetas do limpador","category":"Outros","critical":false},{"id":"3","description":"Nível de fluido de freios","category":"Freios","critical":true}]'::jsonb,
   3, 600)
ON CONFLICT (id) DO NOTHING;
